/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BAI_1_AWT;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Dungna89
 */
public class S5_DemoTongHopCacControls2 extends javax.swing.JFrame {

  DefaultListModel defaultListModel;
  public S5_DemoTongHopCacControls2() {
    initComponents();
    
    defaultListModel = new DefaultListModel();
    String[] arrNames ={"ABC","XYZ"};
    for (String x : arrNames) {
      defaultListModel.addElement(x);
    }
    lst_Name.setModel(defaultListModel);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
   * code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel3 = new javax.swing.JPanel();
    txt_name = new javax.swing.JTextField();
    btn_them = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    lst_Name = new javax.swing.JList<>();
    btn_start = new javax.swing.JButton();
    lbl_PhanTram = new javax.swing.JLabel();
    jProgressBar1 = new javax.swing.JProgressBar();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 36))); // NOI18N
    jPanel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

    txt_name.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

    btn_them.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    btn_them.setText("Thêm");
    btn_them.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_themActionPerformed(evt);
      }
    });

    jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

    lst_Name.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jScrollPane1.setViewportView(lst_Name);

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addComponent(jScrollPane1)
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_them)))
        .addContainerGap(80, Short.MAX_VALUE))
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_them))
        .addGap(26, 26, 26)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
        .addContainerGap())
    );

    btn_start.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    btn_start.setText("Start");
    btn_start.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_startActionPerformed(evt);
      }
    });

    lbl_PhanTram.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
    lbl_PhanTram.setText("0");

    jProgressBar1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(btn_start)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lbl_PhanTram)
                .addGap(43, 43, 43)))
            .addGap(266, 266, 266))
          .addGroup(layout.createSequentialGroup()
            .addGap(118, 118, 118)
            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(25, Short.MAX_VALUE))))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addGap(35, 35, 35)
            .addComponent(btn_start)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(lbl_PhanTram)
            .addGap(111, 111, 111)
            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(388, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
   defaultListModel.addElement(txt_name.getText());
  }//GEN-LAST:event_btn_themActionPerformed

  private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
    var temp = JOptionPane.showConfirmDialog(this,"Bạn có muốn khởi động tiến trình không?","Hỏi chấm?",JOptionPane.YES_NO_OPTION);
    //Sử dụng Thread có được Không?
    if (temp == 0) {
      final Timer t = new Timer(50,new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent e) {
         jProgressBar1.setValue(jProgressBar1.getValue() +1);
         lbl_PhanTram.setText(jProgressBar1.getValue() + " %");

          if (jProgressBar1.getValue() == 100) {
            //((Timer)e.getSource()).stop();
            jProgressBar1.setValue(0);
          }
        }
      });
      t.start();
      
      

    }
  }//GEN-LAST:event_btn_startActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(S5_DemoTongHopCacControls2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(S5_DemoTongHopCacControls2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(S5_DemoTongHopCacControls2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(S5_DemoTongHopCacControls2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new S5_DemoTongHopCacControls2().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_start;
  private javax.swing.JButton btn_them;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JProgressBar jProgressBar1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel lbl_PhanTram;
  private javax.swing.JList<String> lst_Name;
  private javax.swing.JTextField txt_name;
  // End of variables declaration//GEN-END:variables
}
