/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BAI_1_AWT;

import javax.swing.JOptionPane;

/**
 *
 * @author Dungna89
 */
public class S5_DemoTongHopCacControls1 extends javax.swing.JFrame {

  /**
   * Creates new form S5_DemoTongHopCacControls1
   */
  public S5_DemoTongHopCacControls1() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
   * code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    btn_Mess = new javax.swing.JButton();
    btn_confirm = new javax.swing.JButton();
    btn_option1 = new javax.swing.JButton();
    btn_input = new javax.swing.JButton();
    btn_option2 = new javax.swing.JButton();
    txt_text = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dialog", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 36))); // NOI18N
    jPanel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

    btn_Mess.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    btn_Mess.setText("Message");
    btn_Mess.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_MessActionPerformed(evt);
      }
    });

    btn_confirm.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    btn_confirm.setText("Confirm");
    btn_confirm.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_confirmActionPerformed(evt);
      }
    });

    btn_option1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    btn_option1.setText("Option 1");

    btn_input.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    btn_input.setText("Input");
    btn_input.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_inputActionPerformed(evt);
      }
    });

    btn_option2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    btn_option2.setText("Option 2");

    txt_text.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(btn_Mess)
          .addComponent(btn_confirm)
          .addComponent(btn_option1))
        .addGap(32, 32, 32)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(btn_option2)
          .addComponent(btn_input)
          .addComponent(txt_text, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btn_Mess)
          .addComponent(btn_input))
        .addGap(18, 18, 18)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btn_confirm)
          .addComponent(btn_option2))
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(btn_option1))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(24, 24, 24)
            .addComponent(txt_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(54, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(724, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(346, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btn_MessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MessActionPerformed
    JOptionPane.showMessageDialog(this, "Chào các bạn đến với java 3");
  }//GEN-LAST:event_btn_MessActionPerformed

  private void btn_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inputActionPerformed
    String input = JOptionPane.showInputDialog(this, "Bạn có muốn học lại java 3 không?");
    txt_text.setText(input);
  }//GEN-LAST:event_btn_inputActionPerformed

  private void btn_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmActionPerformed
    var temp = JOptionPane.showConfirmDialog(this, "Bạn có chắc là muốn học lại java 3 chứ?");
    if (temp == 1) {
      JOptionPane.showMessageDialog(this, "Bạn sẽ được toại nguyện 1");
    }else if (temp == 0) {
      JOptionPane.showMessageDialog(this, "Bạn sẽ được toại nguyện 0");
    }else {
      JOptionPane.showMessageDialog(this, "Bạn sẽ được toại nguyện 2");
    }
  }//GEN-LAST:event_btn_confirmActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(S5_DemoTongHopCacControls1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(S5_DemoTongHopCacControls1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(S5_DemoTongHopCacControls1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(S5_DemoTongHopCacControls1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new S5_DemoTongHopCacControls1().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_Mess;
  private javax.swing.JButton btn_confirm;
  private javax.swing.JButton btn_input;
  private javax.swing.JButton btn_option1;
  private javax.swing.JButton btn_option2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JTextField txt_text;
  // End of variables declaration//GEN-END:variables
}
